Repository kungbi/NotNginx, pull requests merged in 2025-03, with the labels that each got.

#26 [FEAT] request 와 response 를 관리하는 connection 클래스 구현
  include/webserver/Connection.hpp
  include/webserver/Connections.hpp
  include/webserver/Responses.hpp
  include/webserver/Server.hpp
  src/webserver/Connection.cpp
  src/webserver/Connections.cpp
  src/webserver/Responses.cpp
  src/webserver/Server.cpp
  test/ConnectionTest
  test/ConnectionTest.cpp
  test/ConnectionsTest
  test/ConnectionsTest.cpp
  test/ResponsesTest
  test/ResponsesTest.cpp
Labels: feat

#28 [FEAT] HTTP Request 원문 파싱 적용
  Makefile
  include/request_parser/requestParser.hpp
  include/webserver/Request.hpp
  include/webserver/Requests.hpp
  include/webserver/Server.hpp
  src/request_parser/requestParser.cpp
  src/webserver/Request.cpp
  src/webserver/Requests.cpp
  src/webserver/Server.cpp
  src/webserver/Servers.cpp
  test/RequestParserTest
  test/RequestParserTest.cpp
  test/RequestTest.cpp
Labels: feat

#30 [FEAT] response 인터페이스 구현 및 cgiresponse staticresourceresponse 클래스 구현
  Makefile
  include/webserver/Responses.hpp
  include/webserver/Server.hpp
  include/webserver/connection/Connection.hpp
  include/webserver/connection/Connections.hpp
  include/webserver/connection/Request.hpp
  include/webserver/connection/response/CgiBuffer.hpp
  include/webserver/connection/response/CgiResponse.hpp
  include/webserver/connection/response/Response.hpp
  include/webserver/connection/response/Responses.hpp
  include/webserver/connection/response/StaticResourceResponse.hpp
  src/webserver/Responses.cpp
  src/webserver/Server.cpp
  src/webserver/connection/Connection.cpp
  src/webserver/connection/Connections.cpp
  src/webserver/connection/Request.cpp
  src/webserver/connection/response/CgiBuffer.cpp
  src/webserver/connection/response/CgiResponse.cpp
  src/webserver/connection/response/Responses.cpp
  src/webserver/connection/response/StaticResourceResponse.cpp
  test/CgiBufferTest
  test/CgiBufferTest.cpp
  test/ResponsesTest
  test/ResponsesTest.cpp
Labels: refac, feat

#29 [FEAT] cgi 기능 추가
  include/CGI/CgiExecuter.hpp
  include/CGI/CgiHandler.hpp
  include/webserver/Kqueue.hpp
  src/CGI/CgiExecuter.cpp
  src/CGI/CgiHandler.cpp
Labels: feat

#37 [REFACTOR] 생성된 사용자 응답 데이터 전송 로직 적용
  include/webserver/Server.hpp
  include/webserver/Servers.hpp
  include/webserver/Webserver.hpp
  include/webserver/connection/response/StaticResourceResponse.hpp
  src/webserver/Server.cpp
  src/webserver/Servers.cpp
  src/webserver/Webserver.cpp
  src/webserver/connection/Connection.cpp
  src/webserver/connection/response/StaticResourceResponse.cpp
Labels: refac

#40 [FEAT] StaticResourceHandler 구현
  include/request_handler/StaticResourceHandler.hpp
  src/request_handler/StaticResourceHandler.cpp
  test/StaticResourceHandlerTest
  test/StaticResourceHandlerTest.cpp
  test/test.txt
Labels: feat

#41 [Feat] 라우터 개발
  include/CGI/CgiExecuter.hpp
  include/CGI/CgiHandler.hpp
  include/config/LocationConfig.hpp
  include/config/ServerConfig.hpp
  include/request_parser/RequestParser.hpp
  include/webserver/MimeTypes.hpp
  include/webserver/Router.hpp
  include/webserver/Server.hpp
  src/CGI/CgiExecuter.cpp
  src/CGI/CgiHandler.cpp
  src/config/LocationConfig.cpp
  src/config/ServerConfig.cpp
  src/webserver/Router.cpp
  src/webserver/Server.cpp
  test/RouterTest
  test/RouterTest.cpp
Labels: feat

#44 [FEAT] 핸들러 적용 및 에러 핸들링 적용
  default2.conf
  html/403.html
  html/404.html
  html/50x.html
  html/index.html
  html/styles.css
  include/CGI/CgiExecuter.hpp
  include/config/HTTPConfig.hpp
  include/config/LocationConfig.hpp
  include/config/ServerConfig.hpp
  include/config/WebserverConfig.hpp
  include/request_handler/RequestHandler.hpp
  include/request_handler/StaticResourceHandler.hpp
  include/webserver/HttpExceptions.hpp
  include/webserver/Router.hpp
  include/webserver/Server.hpp
  include/webserver/Servers.hpp
  src/CGI/CgiExecuter.cpp
  src/config/HTTPConfig.cpp
  src/config/LocationConfig.cpp
  src/config/ServerConfig.cpp
  src/config/WebserverConfig.cpp
  src/config_adapter/ConfigAdapter.cpp
  src/main.cpp
  src/request_handler/RequestHandler.cpp
  src/request_handler/StaticResourceHandler.cpp
  src/webserver/MimeTypes.cpp
  src/webserver/Router.cpp
  src/webserver/Server.cpp
  src/webserver/Servers.cpp
  src/webserver/Webserver.cpp
  src/webserver/connection/Connections.cpp
Labels: feat
